### ISSUE TITLE
Protocol Buffers are not designed to handle large messages

### ISSUE THREAD

**Issue by avsej** [couchbase/protostellar#7]
We know for sure that we must support documents up to 20 megabytes, have we considered the notice from Google that the protobuf is not the best solution for large payloads?

https://developers.google.com/protocol-buffers/docs/overview#not-good-fit

> Protocol buffers do not fit all data. In particular:
> 
> Protocol buffers tend to assume that entire messages can be
> loaded into memory at once and are not larger than an object
> graph. For **data that exceeds a few megabytes**, consider a
> different solution; when working with larger data, you may 
> effectively end up with several copies of the data due to
> serialized copies, which can cause surprising spikes in
> memory usage.

https://developers.google.com/protocol-buffers/docs/techniques#large-data

> Protocol Buffers are not designed to handle large messages.
> As a general rule of thumb, if you are dealing in messages
> larger than a megabyte each, it may be time to consider an
> alternate strategy.

**Comment by brett19** [comment]
Closing this issue as discussed in the Protostellar Sync meeting a few weeks ago where it was decided the SDKs will set the buffer size to 21MB by default, and then permit the user to configure this value higher if needed (for large N1QL rows for instance).
